# Generated by Django 5.1.4 on 2024-12-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='cerated_at',
            new_name='created_at',
        ),
    ]
